name: TECHNOVISION - LiteManager

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
      - name: ğŸ“¥ Download & Install Essentials
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/chamod12/lm_win-10_github_rdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: ğŸ”“ Download & Setup Ngrok
        run: |
          Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip" -OutFile "ngrok.zip"
          Expand-Archive ngrok.zip -DestinationPath .
          ./ngrok.exe authtoken YOUR_AUTH_TOKEN

      - name: ğŸš€ Run show.bat
        run: cmd /c show.bat

      - name: ğŸ” Loop Execution
        run: cmd /c loop.bat
